version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 262233964019.dkr.ecr.us-west-1.amazonaws.com/web-app:latest -t 262233964019.dkr.ecr.us-west-1.amazonaws.com/web-app:$COMMIT_HASH .      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 262233964019.dkr.ecr.us-west-1.amazonaws.com/web-app

